#!/usr/bin/env bash
# env の SECRET_* 変数を読み取り、対象スケッチに arduino_secrets.h を生成する。
# 例: SECRET_SSID="foo" -> #define SECRET_SSID "foo"
# 生成ファイルは gitignore 済み。値は mise.local.toml の [env] で管理する。
set -euo pipefail

sketch="${1:?usage: gen-secrets.sh <sketch>}"
dir="sketches/${sketch}"
[ -d "$dir" ] || { echo "error: sketch not found: $dir" >&2; exit 1; }

out="${dir}/arduino_secrets.h"

{
  echo "// AUTO-GENERATED by scripts/gen-secrets.sh"
  echo "// DO NOT EDIT / DO NOT COMMIT. 値は mise.local.toml の [env] で管理する。"
  echo "#pragma once"
  # SECRET_ で始まる環境変数だけを #define 化する。
  for var in $(compgen -e | grep '^SECRET_' || true); do
    val="${!var}"
    # C文字列として安全になるよう \ と " をエスケープする。
    esc=$(printf '%s' "$val" | sed 's/\\/\\\\/g; s/"/\\"/g')
    printf '#define %s "%s"\n' "$var" "$esc"
  done
} > "$out"

echo "generated: $out"
